import {connect} from 'react-redux'
import {bindActionCreators} from 'redux'
import * as actions from '../../actions'
import {TrackPlaylist} from './playlist'
import {TrackPreview} from './preview'
import {TrackStream} from './stream'
